# Generated by Django 3.1.7 on 2021-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_auto_20210501_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='highlight',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='star',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
